name: Package iOS assets
description: Downloads iOS assets and packages them
runs:
  using: composite
  steps:
    - name: Download iOS assets
      uses: actions/download-artifact@v3
      with:
        name: ios-assets
        path: build/ios-assets/
    - name: Create telco-server iOS .deb
      run: |
        mkdir -p build/release-assets
        cd build
        for arch in arm arm64; do
          ../telco-core/tools/package-server-fruity.sh \
              iphoneos-$arch \
              ios-assets \
              release-assets/telco_${TELCO_VERSION}_iphoneos-$arch.deb
        done
      shell: bash
